### ISSUE TITLE
The dats do not work with Retool (1G1R program)

### ISSUE THREAD

**Issue by BobbyBoyGaming** [MetalSlug/MAMERedump#1]
I use Retool to trim down roms I am not interested in having, the program Retool returns an error saying that these DAT files violate the logiqx format.

Is there a way of making these dat files trimmable by Retool?

**Comment by MetalSlug** [comment]
Which dat file violate the logiqx format?
I dont get this error with Retool 1.03. But no titles were found.
Maybe retool will not work with CHD dat files.

At some point I will publish the tools. Then you will be able to use the filtered dat files to create the chd one.

**Comment by BobbyBoyGaming** [comment]
Latest Retool is 1.18
However, the error is only visible when you select a "folder of dats" as source. If you select just a single one of these CHD-dats the program just crashes/closes automatically without posting an error.
It is possible that the Retool 1.03 is simply too old to even report an issue at all and it just tricks you into believing no games are found meeting your selected criteria.

<img width="672" alt="image" src="https://user-images.githubusercontent.com/46551829/222246828-2731ff08-f466-4856-995a-d9d137f9bb66.png">

**Comment by MetalSlug** [comment]
Now it should work with retool 1.18, but retool found no titles.

![grafik](https://github.com/MetalSlug/MAMERedump/assets/5938635/b85265ef-e130-495b-9c47-153430994a16)
