### ISSUE TITLE
Possible issue with Commodore - Amiga CDTV dat

### ISSUE THREAD

**Issue by Daeymon** [MetalSlug/MAMERedump#5]
For the "Commodore - Amiga CDTV" dat, unable to get "Turrican (Germany)" to match. Using RomVault, the source cue/bin matches to the Redump dat but the produced CHD from the latest chdman does not match to the MAMERedump dat.

Update:
Having a closer look. Looks to be a mismatch when merging. Redump's "Turrican (Germany)" has been matched to MAME's "turrican\turrican", which isn't correct.

It should of been matched to MAME's "turrican\turrican (germany)" which has the matching sha to the CHD created from the Redump cue/bin.

**Comment by MetalSlug** [comment]
i will check that. It seems that the data is the same but only metadata is different. Maybe i can prefer the one that has a name match. The wrong one is also marked as a baddump in the orginal mame dat.

`	<game name="turrican\turrican" sha1="7ae052614151cb6e0ad3d1359713c749e398e44f" size="877555" crc="ba7dda7c" fullsha1="58caee214235e499d94f89f7ef6246cd548a9bd3" dataSha1="fb16d4783307181dc87e5b2dec0de0abf3cd50e5">
		<category>Games</category>
		<description>turrican\turrican</description>
		<rom name="turrican (Track 01).bin" size="20815200" crc="d9d2a700" md5="2c5ac366851ae22038a876a0b1e8e579" sha1="ccfb408204450abe929b402bbd3c0b4367376f2f"/>
	</game>
	<game name="turrican\turrican (germany)" sha1="dd65310d53473c9d9d1db0dc344b94c3de6292ae" size="877557" crc="df3f3478" fullsha1="48c9423f28ed9b0bae866844c8647321612450e0" dataSha1="fb16d4783307181dc87e5b2dec0de0abf3cd50e5">
		<category>Games</category>
		<description>turrican\turrican (germany)</description>
		<rom name="turrican (germany) (Track 01).bin" size="20815200" crc="d9d2a700" md5="2c5ac366851ae22038a876a0b1e8e579" sha1="ccfb408204450abe929b402bbd3c0b4367376f2f"/>
	</game>
`

**Comment by Daeymon** [comment]
As an extra thought, maybe priortise the Redump version when the MAME version is flagged as a bad dump?

**Comment by MetalSlug** [comment]
I just excluded the baddumps from matching process. These are also only added with the orginal mame naming when there is no other chd with same fullSha1. I need to rescan ps1 baddumps, but this will need some time. Check the master branch :)
