### ISSUE TITLE
What is the basis for priortising MAME over Redump when merging?

### ISSUE THREAD

**Issue by Daeymon** [MetalSlug/MAMERedump#7]
I only ask since it seems Redump has alot more requirements when accepting a dump over MAME. MAME will allow imperfect dumps if its the best it can get while Redump has a lot of hoops a submission has to pass through before its an accepted dump. That higher level of quality control in my eyes should potentially mean the Redump version should be priortised over the MAME version.

Ultimately, I am sure you have your reasons and its probably a basis that I'm just not aware of. Might be an idea to add the basis to the readme, for others who may have the same question.

**Comment by Daeymon** [comment]
The reason MAME has so many more exclusives, is because MAME has lower standards for the dumps they incorporate into their software lists when compared to Redump. [Give this a read for some insight](https://www.reddit.com/r/MAME/comments/y0zb45/redump_vs_mame/)

I think the PSX dat is a strong example which challenges your basis that the source shouldn't make a difference.

I converted my PSX Redump verfied cue/bin files into CHD. And nearly 2/3 of those files would not verify to the MAMERedump dat. The remaining 2/3 instead verified against the PSX MAME CHDs. If the sources didn't matter, why did the CHDs from Redump not verify while the MAME ones do? Just look at the 007 games for some quick examples.

The only explanation that makes sense to me is that the reason they don't match is because the sources are different. Its what I saw with the PSX dat, that made me wonder what your basis was on picking MAME CHDs over Redump ones when merging.

**Comment by MetalSlug** [comment]
I'll try to recreate some of the 007 games to understand the differences. I assume not all CHDs in Mame are v5 CHDs.

**Comment by MetalSlug** [comment]
Maybe this is the issue:
https://github.com/mamedev/mame/issues/2517

**Comment by Daeymon** [comment]
I would see that as a further argument to priortise Redump over MAME when merging.

**Comment by MetalSlug** [comment]
Short update:
CHDMan creates different metadata in newer versions. So the "very old" chds will become obsolete. The PGSUB Changed from RW to NONE. I need to rebuild most of the mame chds.

Example:
TRACK:1 TYPE:MODE2_RAW SUBTYPE:NONE FRAMES:153917 PREGAP:0 PGTYPE:MODE1 PGSUB:NONE POSTGAP:0.
TRACK:1 TYPE:MODE2_RAW SUBTYPE:NONE FRAMES:153917 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.

I will check the new hashes will match:
https://github.com/mamedev/mame/pull/11252/commits

**Comment by MetalSlug** [comment]
I've updated the hashes for the PlayStation set in the master branch. Can you check whether these now match?
The other sets will follow.

**Comment by Daeymon** [comment]
Tried it with the CHD's I already had. Those did not match to the new dat. So to be thourough, using the latest chdman started recompressing my Redump cue/bin's starting with the "0-9" games and then the "A" games. The newly created CHD's from the same sources are now matching to the new dat. Will continue through the rest but looking good so far.

**Comment by Daeymon** [comment]
Finished recompressing my PSX Redump romset and all of them verified against the new dat within RomVault. So whatever you did, has worked :).
