### ISSUE TITLE
A question about use-cases

### ISSUE THREAD

**Issue by newyokohama** [MetalSlug/MAMERedump#9]
Hey good afternoon, not an issue, but I didn't know another way to ask. Before I flip my sets to CHD, I wanted to ask a question. So for something like Dreamcast/PS1/PS2, would you say that these dats are for:

-Someone who wishes to use redump dumps with MAME.
or
-Someone who uses Dreamcast/PS1/PS2 emulators, and merely wishes to save space for their collection/load into said emulator without having to unzip?

Final question is - in some of those dats I specified, I see almost a complete record mirroring what's on redump.org, but then a whole bunch of entries using what looks like MAME directory names and all kinds of seemingly temporary/random filenames. ie:

```
crash\crash.chd
crash\crashbandicoot.chd
```

I was wondering if those are like something MAME would need for it to work, and that formatting is not only staying, but items like those will increase, or if that's simply like "here's what I have left to process", or something.

And thank you for all your hard work! (If I'm overthinking it, feel free to close. :-) )

Thanks,
-NY

**Comment by MetalSlug** [comment]
Hey,

you can ask in the romvault discord. I am there too :)

These dats are intended to save storage space and most emulators support chds.
So the games can be played directly in the emulator.

The source of this dats is MAME Software List and these chds are matched with redump. Games that are not included have been added. So all mame chds that do not match are arranged in subfolders. It's on my todo list to check deduplication of mostly tosec dumps. Mame is lagging behind in supporting new chds or updating the old ones. I don't even know if some of them work with mame at all. You can ignore these if you only collect redump.
